$(function(){
    $(".wrapper1").scroll(function(){
        $(".wmd-view")
            .scrollLeft($(".wrapper1").scrollLeft());
    });
    $(".wmd-view").scroll(function(){
        $(".wrapper1")
            .scrollLeft($(".wmd-view").scrollLeft());
    });
});